apiVersion: apps/v1
kind: Deployment
metadata:
  name: octohack-front
spec:
  selector:
    matchLabels:
      run: octohack-front
  replicas: 1
  template:
    metadata:
      labels:
        run: octohack-front
    spec:
      containers:
      - name: nginxhttps
        image: us.gcr.io/octohack-220220/octohack-back@sha256:a7cec3ed4567c56be6d5eb08f1ad50098b26b346a64035d19ebfebb6f9dddb8c
        ports:
        - containerPort: 8080
      - name: octohack-front
        image: us.gcr.io/octohack-220220/octohack-front
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: octohack-front
  labels:
    run: octohack-front
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    run: octohack-front
